### ISSUE TITLE
Actualisation d'une "groupe" ne permet pas de charger l'application

### ISSUE THREAD

**Issue by Marc-AntoineA** [MieuxVoter/voterpourleclimat#2]
Quand on rafraîchit une page comme '/se-nourrir', le chargement du user ne se fait pas bien

**Comment by guhur** [comment]
Oui c'est un problème de configuration de netlify

**Comment by guhur** [comment]
Solved in https://github.com/MieuxVoter/voterpourleclimat/commit/f895f705ff2edb6f31b76b6b47614f1057366730
